#!/bin/bash

build() {
    local applet

    add_binary /usr/lib/initcpio/busybox /bin/busybox

    for applet in $(/usr/lib/initcpio/busybox --list); do
        add_symlink "/usr/bin/$applet" busybox
    done

    add_binary mount
    add_binary findmnt
    add_binary /usr/lib/systemd/systemd-shutdown /bin

    add_file "/usr/lib/initcpio/sqsh-shutdown" "/shutdown"
}

help() {
    cat <<HELPEOF
This hook creates a ramdisk that cleanly umounts the image source fs
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
